owner: tyis
repo: status-tyis-co-jp

sites:
  - name: TOYO Internet Service
    url: https://www.tyis.co.jp
  - name: TOYO Consultancy Services Korea
    url: https://www.toyocs.net
  - name: Recycle Pocket
    url: https://www.recyclepocket.com
  - name: 産廃見積.com
    url: https://産廃見積.com
  - name: TOYO Cloud
    url: https://cloud.tyis.co.jp
  - name: TOYO Hosting
    url: https://hosting.tyis.co.jp
  - name: Redmine
    url: https://redmine.tyis.co.jp

status-website:
  cname: status.tyis.co.jp
  name: TOYO Internet Service Status
  i18n:
    footer: "&copy; 2026. TOYO Internet Service Co., Ltd. &#124; Love this planet&#10084;&#65039; Operated by TOYO Dev Team."
